#!/bin/bash
# shellcheck disable=SC2154
# shellcheck disable=SC1111
# Include pashua.sh to be able to use the 2 functions defined in that file

cd "$(dirname "$0")" || exit

exec &> >(tee -a ~/Library/Logs/naisdevice-nav-mac-up.log)

source user-choices.sh

#if [[ "$repo" = "1" ]]; then
#    source get-repo-url.sh
#    if [[ "$cb" = "1" ]]; then
#        exit 0
#    fi
#fi

# Check if user has some taps of their own
if [[ "$brew" = "1" ]]; then
    source taps.sh
    if [[ "$cb" = "1" ]]; then
        exit 0
    fi
fi

open naisdevice-nav-mac-up.command
